https://www.cdc.gov/measles/data-research/index.html

In [1]:
import pandas as pd
import plotly.express as px

# Most Affected U.S. States Data

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/measles_data/refs/heads/main/Top_states_time_series.csv')

## Data Restructuring and Preprocessing

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   week_start  82 non-null     object
 1   week_end    82 non-null     object
 2   FL_cases    82 non-null     int64
 3   VA_cases    82 non-null     int64
 4   TX_cases    82 non-null     int64
 5   AZ_cases    82 non-null     int64
 6   UT_cases    82 non-null     int64
 7   SC_cases    82 non-null     int64
dtypes: int64(6), object(2)
memory usage: 5.3+ KB

In [ ]:
df.head()

,week_start,week_end,FL_cases,VA_cases,TX_cases,AZ_cases,UT_cases,SC_cases
0,2025-01-05,2025-01-11,0,0,0,0,0,0
1,2025-01-12,2025-01-18,0,0,0,0,0,0
2,2025-01-19,2025-01-25,0,0,11,0,0,0
3,2025-01-26,2025-02-01,0,0,20,0,0,0
4,2025-02-02,2025-02-08,0,0,27,0,0,0

In [ ]:
df.tail()

,week_start,week_end,FL_cases,VA_cases,TX_cases,AZ_cases,UT_cases,SC_cases
77,2026-06-28,2026-07-04,0,16,0,2,3,0
78,2026-07-05,2026-07-11,0,32,0,3,3,0
79,2026-07-12,2026-07-18,0,0,1,10,1,0
80,2026-07-19,2026-07-25,0,0,5,9,1,0
81,2026-07-26,2026-08-01,0,0,0,0,0,0

In [ ]:
florida_df = df[['week_start', 'week_end', 'FL_cases']].copy()
florida_rolling = florida_df['FL_cases'].rolling(window=7).mean()

combined_fl = pd.concat([florida_df['week_start'], florida_rolling], axis=1)

In [ ]:
virginia_df = df[['week_start', 'week_end', 'VA_cases']].copy()
va_rolling = virginia_df['VA_cases'].rolling(window=7).mean()

combined_va = pd.concat([virginia_df['week_start'], va_rolling], axis=1)

In [ ]:
texas_df = df[['week_start', 'week_end', 'TX_cases']].copy()
tx_rolling = texas_df['TX_cases'].rolling(window=7).mean()

combined_tx = pd.concat([texas_df['week_start'], tx_rolling], axis=1)

In [ ]:
arizona_df = df[['week_start', 'week_end', 'AZ_cases']].copy()
az_rolling = arizona_df['AZ_cases'].rolling(window=7).mean()

combined_az = pd.concat([arizona_df['week_start'], az_rolling], axis=1)

In [ ]:
utah_df = df[['week_start', 'week_end', 'UT_cases']].copy()
ut_rolling = utah_df['UT_cases'].rolling(window=7).mean()

combined_ut = pd.concat([utah_df['week_start'], ut_rolling], axis=1)

In [ ]:
sc_df = df[['week_start', 'week_end', 'SC_cases']].copy()
sc_rolling = sc_df['SC_cases'].rolling(window=7).mean()

combined_sc = pd.concat([sc_df['week_start'], sc_rolling], axis=1)

In [ ]:
combined_df = pd.concat([df['week_start'], florida_rolling, va_rolling, tx_rolling, az_rolling, ut_rolling, sc_rolling], axis=1)

combined_df

    week_start  FL_cases   VA_cases  TX_cases  AZ_cases  UT_cases  SC_cases
0   2025-01-05       NaN        NaN       NaN       NaN       NaN       NaN
1   2025-01-12       NaN        NaN       NaN       NaN       NaN       NaN
2   2025-01-19       NaN        NaN       NaN       NaN       NaN       NaN
3   2025-01-26       NaN        NaN       NaN       NaN       NaN       NaN
4   2025-02-02       NaN        NaN       NaN       NaN       NaN       NaN
..         ...       ...        ...       ...       ...       ...       ...
77  2026-06-28  0.285714  15.714286  0.142857  0.285714  4.000000  0.285714
78  2026-07-05  0.142857  19.571429  0.000000  0.714286  4.000000  0.285714
79  2026-07-12  0.142857  16.142857  0.142857  2.142857  3.714286  0.142857
80  2026-07-19  0.000000  12.285714  0.857143  3.428571  2.428571  0.000000
81  2026-07-26  0.000000   9.428571  0.857143  3.428571  1.714286  0.000000

[82 rows x 7 columns]

## Data Visualization (Plotly)

In [ ]:
fig = px.bar(combined_fl, x=combined_fl['week_start'], y=combined_fl['FL_cases'],
             labels={'week_start' : 'Start Date of the Week',
                     'FL_cases' : 'Cases (Moving Average)'},
             title='Measles Cases in Florida')

fig.show()

In [ ]:
fig = px.bar(combined_va, x=combined_va['week_start'], y=combined_va['VA_cases'],
             labels={'week_start' : 'Start Date of the Week',
                     'VA_cases' : 'Cases (Moving Average)'},
             title='Measles Cases in Virginia')

fig.show()

In [ ]:
fig = px.bar(combined_tx, x=combined_tx['week_start'], y=combined_tx['TX_cases'],
             labels={'week_start' : 'Start Date of the Week',
                     'TX_cases' : 'Cases (Moving Average)'},
             title='Measles Cases in Texas')

fig.show()

In [ ]:
fig = px.bar(combined_az, x=combined_az['week_start'], y=combined_az['AZ_cases'],
             labels={'week_start' : 'Start Date of the Week',
                     'AZ_cases' : 'Cases (Moving Average)'},
             title='Measles Cases in Arizona')

fig.show()

In [ ]:
fig = px.bar(combined_ut, x=combined_ut['week_start'], y=combined_ut['UT_cases'],
             labels={'week_start' : 'Start Date of the Week',
                     'UT_cases' : 'Cases (Moving Average)'},
             title='Measles Cases in Utah')

fig.show()

In [ ]:
fig = px.bar(combined_sc, x=combined_sc['week_start'], y=combined_sc['SC_cases'],
             labels={'week_start' : 'Start Date of the Week',
                     'SC_cases' : 'Cases (Moving Average)'},
             title='Measles Cases in South Carolina')

fig.show()

In [ ]:
name_map = {
    'FL_cases' : 'Florida',
    'VA_cases' : 'Virginia',
    'TX_cases' : 'Texas',
    'AZ_cases' : 'Arizona',
    'UT_cases' : 'Utah',
    'SC_cases' : 'South Carolina',
}

fig = px.bar(combined_df, x=combined_df['week_start'], y=['FL_cases', 'VA_cases', 'TX_cases', 'AZ_cases', 'UT_cases', 'SC_cases'],
                labels={'variable' : 'State',
                        'week_start' : 'Start Date of Week',
                        'value' : 'Moving Average of Cases'},
                title='Measles Cases in Most Affected U.S. States')

for trace in fig.data:
  clean_name = name_map.get(trace.name, trace.name)
  trace.name = clean_name
  trace.hovertemplate = f"<b>{clean_name}</b><br>Start Date of Week=%{{x}}<br>Moving Average of Cases=%{{y}}<extra></extra>"

fig.show()

# All States Measles Data

In [ ]:
all = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/measles_data/refs/heads/main/measles_county_all_updates_detailed.csv')

## Data Restructuring and Preprocessing

In [ ]:
all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2865 entries, 0 to 2864
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_name  2865 non-null   object
 1   location_id    2855 non-null   float64
 2   location_type  2865 non-null   object
 3   date           2865 non-null   object
 4   outcome_type   2865 non-null   object
 5   value          2865 non-null   int64
dtypes: float64(1), int64(1), object(4)
memory usage: 134.4+ KB

In [ ]:
all.head()

,location_name,location_id,location_type,date,outcome_type,value
0,"Adams, Colorado",8001.0,county,2025-08-13,case_imported,1
1,"Adams, Colorado",8001.0,county,2025-08-13,case_lab-confirmed,1
2,"Adams, Colorado",8001.0,county,2025-08-13,case_unvaccinated,1
3,"Adams, Colorado",8001.0,county,2025-08-15,case_lab-confirmed,2
4,"Adams, Colorado",8001.0,county,2025-08-15,case_local,2

In [ ]:
all.tail()

,location_name,location_id,location_type,date,outcome_type,value
2860,"York, Pennsylvania",42133.0,county,2026-07-01,case_local,1
2861,"York, Pennsylvania",42133.0,county,2026-07-22,case_lab-confirmed,1
2862,"York, Pennsylvania",42133.0,county,2026-07-22,case_local,1
2863,"York, Pennsylvania",42133.0,county,2026-07-31,case_lab-confirmed,4
2864,"York, Pennsylvania",42133.0,county,2026-07-31,case_local,4

In [ ]:
all.isna().any()

location_name    False
location_id       True
location_type    False
date             False
outcome_type     False
value            False
dtype: bool

In [ ]:
all = all.drop(columns=['location_id', 'location_type'])

all

           location_name        date        outcome_type  value
0        Adams, Colorado  2025-08-13       case_imported      1
1        Adams, Colorado  2025-08-13  case_lab-confirmed      1
2        Adams, Colorado  2025-08-13   case_unvaccinated      1
3        Adams, Colorado  2025-08-15  case_lab-confirmed      2
4        Adams, Colorado  2025-08-15          case_local      2
...                  ...         ...                 ...    ...
2860  York, Pennsylvania  2026-07-01          case_local      1
2861  York, Pennsylvania  2026-07-22  case_lab-confirmed      1
2862  York, Pennsylvania  2026-07-22          case_local      1
2863  York, Pennsylvania  2026-07-31  case_lab-confirmed      4
2864  York, Pennsylvania  2026-07-31          case_local      4

[2865 rows x 4 columns]

In [ ]:
states_names = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

filter = []

for state in states_names:
  state = all[all['location_name'].str.contains(state)]
  filter.append(state)

states = pd.concat(filter)

## Data Visualizations (Plotly)

In [ ]:
states['outcome_type'] = states['outcome_type'].replace({'case_imported' : 'Imported',
                                         'case_lab-confirmed' : 'Lab (Confirmed)',
                                         'case_local' : 'Local',
                                         'case_unvaccinated' : 'Unvaccinated',
                                         'case_vaccinated' : 'Vaccinated'})

In [ ]:
outcome = states.groupby('outcome_type', as_index=False)['value'].sum()

fig = px.bar(outcome, x='outcome_type', y='value',
             labels={'outcome_type' : 'Case Type',
                     'value' : 'Count'},
             title='Measles Case Type in U.S. (Imported, Local, Vaccinated, Unvaccinated, Lab (Confirmed))')

fig.show()

In [ ]:
states_df = states.copy()

states_df[['County', 'State']] = states_df['location_name'].str.split(', ', expand=True)
states_df = states_df.drop(columns=['County', 'location_name'])

states_df = states_df.groupby('State', as_index=False)['value'].sum()

                   State  value
0                Alabama      2
1                 Alaska     11
2                Arizona    937
3               Arkansas     21
4             California    173
5               Colorado    152
6            Connecticut      9
7               Delaware     20
8   District of Columbia      4
9                Florida    296
10               Georgia     44
11                Hawaii      8
12                 Idaho     71
13              Illinois     38
14               Indiana     28
15                  Iowa     30
16                Kansas    184
17              Kentucky     40
18             Louisiana      9
19                 Maine     14
20              Maryland     30
21         Massachusetts      4
22              Michigan     91
23             Minnesota    101
24              Missouri     22
25               Montana     87
26              Nebraska     14
27                Nevada      6
28            New Jersey     27
29            New Mexico    267
30              New York    132
31        North Carolina     53
32          North Dakota    221
33                  Ohio    134
34              Oklahoma     51
35                Oregon     71
36          Pennsylvania    387
37          Rhode Island      7
38        South Carolina   2949
39          South Dakota     78
40             Tennessee     29
41                 Texas   1987
42                  Utah   1533
43               Vermont      8
44              Virginia    364
45            Washington    151
46             Wisconsin    112
47               Wyoming     52

In [ ]:
fig = px.bar(states_df, x='State', y='value',
             labels={'value' : 'Number of Cases'},
             title='Number of Measles Cases in Every U.S. State')

fig.show()

In [ ]:
dates_df = states.copy()
dates_df[['County', 'State']] = dates_df['location_name'].str.split(', ', expand=True)
dates_df = dates_df.drop(columns=['County', 'location_name'])

dates_df = dates_df.groupby('date', as_index=False)['value'].sum()

In [ ]:
fig = px.bar(dates_df, x='date', y='value',
             labels={'date' : 'Date',
                     'value' : 'Number of Measles Cases'},
             title='Number of Measles Cases (2025-2026)')

fig.show()